name: odata_helper
description: OData (v4.01) client-side code generator
version: 0.0.1
homepage: https://github.com/theirontnt/odata_helper

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.5
  lints: ^1.0.0
  test: ^1.20.2

dependencies:
  build: ^2.2.1
  built_collection: ^5.1.1
  source_gen: ^1.2.1
  source_helper: ^1.3.1
  decimal: ^2.1.0
  pubspec_parse: ^1.2.0
  flat: ^0.4.1
  json_annotation: ^4.4.0
  http: ^0.13.4
