name: odata_helper
description: OData client-side code generator
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0

dependencies:
  build_runner: ^2.1.7
