name: odata_helper
description: OData (v4.01) client-side code generator
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0

dependencies:
  build: ^2.2.1
  built_collection: ^5.1.1
  source_gen: ^1.2.1
  source_helper: ^1.3.1
  decimal: ^2.1.0
